# Arquivo para filtrar o json com as colunas selecionadas
def colunas_dfuncionarios(record):
    return {
        'Id': record.get('Id'),
        'Nome': record.get('Nome'),
        'NumeroFolha': record.get('NumeroFolha'),
        'Endereco': record.get('Endereco'),
        'Bairro': record.get('Bairro'),
        'Uf': record.get('Uf'),
        'Cep': record.get('Cep'),
        'Telefone': record.get('Telefone'),
        'Celular': record.get('Celular'),
        'Email': record.get('Email'),
        'Cpf': record.get('Cpf'),
        'Nascimento': record.get('Nascimento'),
        'Masculino': record.get('Masculino'),
        'Admissao': record.get('Admissao'),
        'Demissao': record.get('Demissao'),
        'EmpresaId': record.get('EmpresaId'),
        'HorarioId': record.get('HorarioId'),
        'DepartamentoId': record.get('DepartamentoId'),
        'FuncaoId': record.get('FuncaoId'),
        'MotivoDemissaoId': record.get('MotivoDemissaoId'),
        'Empresa.Id': record.get('Empresa', {}).get('Id'),
        'Empresa.Nome': record.get('Empresa', {}).get('Nome'),
        'Empresa.Documento': record.get('Empresa', {}).get('Documento'),
        'Empresa.Inscricao': record.get('Empresa', {}).get('Inscricao'),
        'Empresa.Endereco': record.get('Empresa', {}).get('Endereco'),
        'Empresa.Bairro': record.get('Empresa', {}).get('Bairro'),
        'Empresa.Cep': record.get('Empresa', {}).get('Cep'),
        'Empresa.Uf': record.get('Empresa', {}).get('Uf'),
        'Empresa.Pais': record.get('Empresa', {}).get('Pais'),
        'Empresa.Telefone': record.get('Empresa', {}).get('Telefone'),
        'Empresa.ResponsavelNome': record.get('Empresa', {}).get('ResponsavelNome'),
        'Empresa.ResponsavelCargo': record.get('Empresa', {}).get('ResponsavelCargo'),
        'Empresa.ResponsavelEmail': record.get('Empresa', {}).get('ResponsavelEmail'),
        'Horario.Id': record.get('Horario', {}).get('Id'),
        'Horario.Numero': record.get('Horario', {}).get('Numero'),
        'Horario.Descricao': record.get('Horario', {}).get('Descricao'),
        'Departamento.Id': record.get('Departamento', {}).get('Id'),
        'Departamento.Descricao': record.get('Departamento', {}).get('Descricao'),
        'Departamento.Nfolha': record.get('Departamento', {}).get('Nfolha'),
        'Funcao.Id': record.get('Funcao', {}).get('Id'),
        'Funcao.Descricao': record.get('Funcao', {}).get('Descricao'),
    }


# Filtrar colunas da folha de ponto
def colunas_folhaPonto(record):
    return {
        'Id': record.get('Id'),
        'FuncionarioId': record.get('FuncionarioId'),
        'Data': record.get('Data'),
        'Entrada1': record.get('Entrada1'),
        'Saida1': record.get('Saida1'),
        'Entrada2': record.get('Entrada2'),
        'Saida2': record.get('Saida2'),
        'Folga': record.get('Folga'),
        'MemoriaEntrada1': record.get('MemoriaEntrada1'),
        'MemoriaSaida1': record.get('MemoriaSaida1'),
        'MemoriaEntrada2': record.get('MemoriaEntrada2'),
        'MemoriaSaida2': record.get('MemoriaSaida2'),
    }

