TABELA_PONTO = 'TB_API_PONTO'

PEGAR_INTERVALO =f"""

DECLARE @DataMax DATETIME;
SELECT @DataMax = MAX(CONVERT(DATETIME, Data, 126)) 
FROM {TABELA_PONTO};

DECLARE @DataMin DATETIME;
SET @DataMin = DATEADD(MONTH, -2, @DataMax);

SELECT @DataMin AS DataInicial, @DataMax AS DataFinal;

"""

DELETAR_INTERVALO = f"""

DECLARE @DataMax DATETIME;
SELECT @DataMax = MAX(CONVERT(DATETIME, Data, 126)) 
FROM {TABELA_PONTO};

DECLARE @DataMin DATETIME;
SET @DataMin = DATEADD(MONTH, -2, @DataMax);

DELETE FROM {TABELA_PONTO}
WHERE Data BETWEEN @DataMin AND @DataMax;

"""